GET http://localhost:5000/api/developers/getDevs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjUyMjI0NGVhMzk5NzU3NzY1MzY1NyIsInVzZXJuYW1lIjoiQ0VPQE9HVCIsImlhdCI6MTY4OTc1NzI0M30.4HLFH0kIuUwqZ0af6IHHEdGuPrig7FzojrDwQA_6lRw

###
POST http://localhost:5000/api/developers/login
Content-Type: application/json

{
    "username":"CEO@OGT",
    "password":"12345678"
}